Activate async test
geopython/pywps pull request #664
Opened 2022-09-19 21:06 UTC by huard

# Overview
A unit test for asynchronous processes was not actually running asynchronously. The test now runs in async mode and will raise an error if it ever runs synchronously. 

# Related Issue / Discussion
In response to comments in #657

# Additional Information
Depends on #663 

# Contribution Agreement

(as per https://github.com/geopython/pywps/blob/master/CONTRIBUTING.rst#contributions-and-licensing)

- [x] I'd like to contribute [feature X|bugfix Y|docs|something else] to PyWPS. I confirm that my contributions to PyWPS will be compatible with the PyWPS license guidelines at the time of contribution.
- [x] I have already previously agreed to the PyWPS Contributions and Licensing Guidelines

2022-10-18 14:59 UTC, gschwind requested changes
Hello

Thank for the fix :)

The while loop is too simple, It need to handle a time out to avoid infinite waiting, and it also need check for Failed status.

Otherwise pytest is working, when test do not fail :)

Best regards.

2022-10-19 17:41 UTC, huard commented
Done

2022-10-20 08:42 UTC, gschwind approved these changes
Look good to me

Maybe you should capitalise commit messages :)

Best regards

2023-01-27 17:44 UTC, cehbrecht approved these changes

2023-01-27 17:50 UTC, merged

2023-01-27 17:50 UTC, cehbrecht commented
@huard thanks :)